### ISSUE TITLE
DI for Breadcumbs

### ISSUE THREAD

**Issue by korteksz** [jnprr/blazor-breadcrumb-navigation#5]
Hello,

I want to use localized breadcumbs and I can't find a way to inject an IStringLocalizer instance into my breadcumb implementations. Is it somehow possible now? 

Thanks for your answer!

**Comment by cschulzsuper** [comment]
This should work out of the box. All breadcrumbs are basically blazor components which support property injection.

The following should work just find, when added as a property in your breadcrumb.

``` csharp
[Inject]
public IStringLocalizer<YourBreadcrumb> Localizer { get; set; }
```

**Comment by korteksz** [comment]
Ah okay, I'm still new in Blazor and I haven't noticed it! 

Thank you very much for your support, it is working just fine!
