### ISSUE TITLE
Feature Request: Unseal BreadcrumbNavigation class

### ISSUE THREAD

**Issue by leijae** [jnprr/blazor-breadcrumb-navigation#7]
It would be nice to able to custom style more of the tree, and use ol instead of ul if I wanted to... 

Unsealing the class so that various methods can be overwritten would be very nice.

**Comment by cschulzsuper** [comment]
As soon as I find a time slot, I'll look into that request.

**Comment by cschulzsuper** [comment]
I removed the seal of the `BreadcrumbNavigation` component and created a new version of the package.
