### ISSUE TITLE
Don't add breadcrumb when it is already in collection

### ISSUE THREAD

**Issue by alexkleinwaechter** [jnprr/blazor-breadcrumb-navigation#9]
Hi,
perhaps I misunderstood something, but if I navigate back in my breadcrumbs the clicked breadcrumb will be added again which looks awkward:
Home/Finanzpläne/Konsolidierungsblätter/Konsolidierungsdetails/Konsolidierungsblätter/Konsolidierungsblatt/Konsolidierungsblätter
Can I do something against that behaviour?
I think your Add Method should check if the URL is already in the breadcrumb array and only add if its not the case.

Best!
Alex

**Comment by cschulzsuper** [comment]
Hello Alex,

I think what you trying to do is not supported by this component. The breadcrumb navigation itself does not evaluate navigation events and resets them if you navigate back.

The breadcrumb trail needs to be rewritten on every page.

In your given example this would mean that **Konsolidierungsblätter** needs to set up a trail like this.

``` csharp
    BreadcrumbService
        .Set<HomeBreadcrumb>()
        .Set<FinanzplaeneBreadcrumb>()
        .Set<KonsolidierungsblaetterBreadcrumb>();
```
While **Konsolidierungsblatt** needs to setup the whole trail like this.

``` csharp
    BreadcrumbService
        .Set<HomeBreadcrumb>()
        .Set<FinanzplaeneBreadcrumb>()
        .Set<KonsolidierungsblaetterBreadcrumb>()
        .Set<KonsolidierungsblattBreadcrumb>();
```

Keep in mind that `HomeBreadcrumb` needs to be derived from `RootBreadcrumb`.
